config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ContentfulModel::Base
  self.content_type_id = "recipe"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all.paginate(page, per_page).load
  end

  def show
    @recipe = Recipe.find(params[:id])
  end


  private

  def page
    params[:page] || 1
  end

  def per_page
    params[:per_page] || 20
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- Begin Bootstrap Navbar -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Recipes</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <!-- End Bootstrap Navbar -->
    <%= yield %>
  </body>
</html>

app/views/recipes/_details.html.erb
<div class="row">
  <div class="col-sm-4">
    <img src="<%= @recipe.photo.url %>" width="400">
  </div>
  <div class="col-sm-4">
    <p><strong> <%= @recipe.title %></strong></p>
    <% if @recipe.chef.present? %>
        <p> By: <%= @recipe.chef.name %> </p></br>
    <%end%>
    <p> <%= @recipe.description %> </p>
    <p>
      <% @recipe.tags&.each do |tag| %>
          <a href="#">#<%= tag.name %></a>
      <%end%>
    </p>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="row text-center">
  <% @recipes.each do |recipe| %>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="<%= recipe.photo.url %>" width="400">
        <p><strong> <%= recipe.title %></strong></p>
        <a href="<%=recipe_path(recipe.id) %>"><button class="btn btn-dark" >View Recipe</button></a>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<% if @recipe.blank? %>
  <h2>Invalid Recipe</h2>
<% else %>
 <%= render "details" %>
<% end %>